<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class CategoryController extends Controller
{
    public function index()
    {
        // return parent::index(); // TODO: Change the autogenerated stub

    }
}
